name: "dashboard"
aliases:
  - "dash"
domain: "dashboard.roadtotech.me"
description: "Homelab Service Dashboard & Application Launcher"
visible: false
auth: false
networks:
  - proxy-net
  - socket-net
env:
  LEARNING_DOMAIN: "learning.roadtotech.me"
